import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'BlogLayout | Create Next App',
  description: 'BlogLayout - Generated by create next app',
  keywords: ['Next.js', 'React', 'JavaScript'],
}


export default function BlogLayout({children}: {children: React.ReactNode}) {
    return <div>
<h2>Blog</h2>
{children}
    </div>
}